language: python

python:
  - "2.7"
  
services:
  - docker
  
install:
  - docker build -t container-helloworld .
  - docker run container-helloworld
  - docker ps -a
  
script: 
  - python hello.py
